<?php
require __DIR__ . '/config/app.php';
$user = require_user('practitioner');
$page = 'practice';
$title = 'Practitioner Dashboard';
$cases = db()->query('SELECT c.*, u.name AS client_name FROM client_cases c JOIN users u ON u.id = c.client_id ORDER BY c.id DESC')->fetchAll();
$contacts = db()->query('SELECT * FROM contact_requests ORDER BY id DESC LIMIT 6')->fetchAll();
include __DIR__ . '/templates/header.php';
?>
<div class="app-shell"><aside class="app-sidebar"><span class="role-tag">Practitioner account</span><div class="user-block"><div class="avatar"><?= e(substr($user['name'], 0, 1)) ?></div><div><div class="name"><?= e($user['name']) ?></div><div class="sub"><?= e($user['email']) ?></div></div></div><nav class="side-nav"><a class="active" href="#">Overview</a><a href="research.php">Research</a><a href="assistant.php">AI Assistant</a><a href="logout.php">Sign out</a></nav></aside><div class="app-main"><div class="app-header"><div><h1>Welcome back, <?= e(strtok($user['name'], ' ')) ?></h1><p class="meta">Client matters and incoming consultation requests.</p></div></div><div class="stat-grid"><div class="stat-card"><div class="stat-value"><?= count($cases) ?></div><div class="stat-label">Client matters</div></div><div class="stat-card"><div class="stat-value"><?= count($contacts) ?></div><div class="stat-label">Recent requests</div></div><div class="stat-card"><div class="stat-value">3</div><div class="stat-label">Verified profile signals</div></div><div class="stat-card"><div class="stat-value">SQLite</div><div class="stat-label">Storage</div></div></div><div class="panel"><div class="panel-head"><h3>Client cases</h3></div><table class="data-table"><thead><tr><th>Client</th><th>Case</th><th>Next step</th><th>Status</th></tr></thead><tbody><?php foreach ($cases as $case): ?><tr><td><?= e($case['client_name']) ?></td><td><?= e($case['title']) ?></td><td><?= e($case['next_step']) ?></td><td><span class="status-pill status-<?= strtolower($case['status']) === 'active' ? 'active' : (strtolower($case['status']) === 'pending' ? 'pending' : 'closed') ?>"><?= e($case['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="panel" style="margin-top:18px"><h3>Consultation requests</h3><?php foreach ($contacts as $contact): ?><div class="doc-row"><div class="doc-info"><div class="doc-name"><?= e($contact['subject']) ?></div><div class="doc-meta"><?= e($contact['name']) ?> · <?= e($contact['email']) ?></div></div></div><?php endforeach; ?></div></div></div>
<?php include __DIR__ . '/templates/footer.php'; ?>
